### ISSUE TITLE
Add app to PlayStore

### ISSUE THREAD

**Issue by Glitchy-Tozier** [yakovlevegor/DroidRec#12]
This would make the app accessible to more people.

**Comment by yakovlevegor** [comment]
I just don't think I could maintain the app in the Play Store well. And I don't think it's a good idea to put the app on Play Store just to get more people to use it.

**Comment by Glitchy-Tozier** [comment]
Shouldn't there be an automated way of pushing updates to the Play Store, just as there is for Fdroid?

In case you don't want to entertain the thought, just close the issue :)

**Comment by yakovlevegor** [comment]
Then it's settled.

**Comment by cvzi** [comment]
I could publish and maintain your app on the Play Store on my own Google account (I have two of my own apps there), if you are ok with that.

**Comment by cvzi** [comment]
Thanks, so I started adding it to Google but there is a problem:

I had thought, I would just use your signed .apk files, but Google wants a signed app bundle (.aab-file). Apparently Google doesn't allow uploading .apk for new apps anymore.

If you want to release signed .aab files with your releases you could create them like this:

```bash
# create bundle in app/build/outputs/bundle/release/app-release.aab
gradle bundleRelease
# Sign 'app-release.aab' with keystore 'my.keystore'
jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 -keystore my.keystore -storepass mystorepassword -keypass mykeypassword app-release.aab mykeyalias

```

If you don't want to release .aab files with your Github releases, I'll just build and sign the bundles myself.

**Comment by yakovlevegor** [comment]
I think it's better to use a separate signature for Play Store release, after all it's not official. As for bundles, sure I'll release them.

**Comment by yakovlevegor** [comment]
If you need unsigned builds, I'll provide them as well.

**Comment by cvzi** [comment]
I think it would be best if you provide the signed bundle in your Github releases.

Then I download your bundle, verify the signature, sign it with my own key and upload to Google.

Google uses their own key for distribution anyway, they just want a signed bundle to verify the uploaded file is from the same person every release. They still need to distribute an apk file to the users not the bundle. So they need to generate and sign apk files themselves from the bundle. Even if I would upload a bundle signed with your key, the apk that Google sends to the user has a "Google signature".

**Comment by yakovlevegor** [comment]
Added .aab to [release assets](https://github.com/yakovlevegor/DroidRec/releases/tag/v3.2).

**Comment by yakovlevegor** [comment]
Also made a quick bundle signature script.

**Comment by drogga** [comment]
@cvzi - Pls. post a link to your developer account here...
I wonder what will happen if and when you decide to make $ from this and inject garbage, like analytics, ADs, in-app purchases or make it paid, those are things that the owner here should consider, also it's not a good idea to use a diff. signature/certificate, probably a key rotation can be used, but it only supports scheme v3 (Android 9+) and it's not a good idea to hand over the distribution to someone else, especially the signature/certificate, along with its key and alias pass, because a bad things can happen and it might end up in a bad situation.
I don't thing that you completely understand the Play Store's dev. console and how it works, because you should be able to make it so it distributes .apk files with a personal and custom signature, instead of Google's, but the bundles that PS provides \ installs on the devices will still be generated and signed by them with the key\cert that they will generate and use, PS very rarely provides single standalone .apk files, especially for apps that require A.5.0+, like this one, the PS app will instead push \ DL and install bundles (not .aab) in the form of split APKs on the most devices, those contain base, dpi, libs (cpu arch), languages and assets. Overall it's a bad idea for someone else to distribute your apps\games, because I've seen this go really bad for some, then there can be ownership claims, lawsuits and whatever else.

**Comment by yakovlevegor** [comment]
I just *can't* release it on Google Play, because of Google Pay ban in russia and my general bad attitude towards Google services. I don't own the DroidRec name, I didn't copyright it. If @cvzi decides to make money off it, I bet there would be another app published on Play Store (maybe with a slightly different name), because the code is Public Domain. As I said, I don't care what happens on Play Store, heck I couldn't care less.

**Comment by drogga** [comment]
Oh, OK, NVM then.

**Comment by yakovlevegor** [comment]
And I have seen some practices of idiots stealing Open-Source apps, like, for example, stealing VLC source code, slightly customizing the interface, and then selling it as proprietary. But it's definitely **not** our situation here.

**Comment by drogga** [comment]
Pls check my edited comment ^ with a link.

**Comment by yakovlevegor** [comment]
Okay, noted. Thanks for publishing, @cvzi. Gonna try it, haha. 😄

**Comment by drogga** [comment]
I wonder why there are so many repeated (the exact same) screenshots images on PS...

**Comment by drogga** [comment]
You can close this...

**Comment by yakovlevegor** [comment]
Added Play Store release link to README. Closing.

**Comment by cvzi** [comment]
> I wonder why there are so many repeated (the exact same) screenshots images on PS...

Google wanted separate screenshots for "Phone",  "Tablet 7 inch", "Tablet 10 inch" and "Chromebook". Since I only had phone screenshots, I just uploaded the phone screenshot for all of them. I didn't realize Google shows all of them at the same time, I thought they just show the screenshots for one device category 🤦‍ I'll fix that later.

Regarding copies on the Play Store:
My app "Screenshot Tile" is licensed under GPL and I have seen a few copies with ads or crypto mining published on the Play Store. They change the name and description and sometimes change the text/strings in the app. They also remove the copyright notice or they don't state that they modified the app, which violates GPL license. When I reported them to Google for violating the license, Google just requests screenshots as proof. It was still obvious from screenshots that it was the same app. Then Google has always removed the app within a few days.
But I stopped reporting them after a few months, because it's just too much work to look for these copies and report them. 

> because of Google Pay ban in russia 

But the Play Store is still accessible in Russia for users?

**Comment by yakovlevegor** [comment]
> But the Play Store is still accessible in Russia for users?

@cvzi, yes, free Google services are still fully accessible in russia. What doesn't work is Google Pay (because of Swift cut-off) and people been reporting their bought apps not getting updates anymore.
