### ISSUE TITLE
Crash on Android 9 when recording more than once

### ISSUE THREAD

**Issue by yakovlevegor** [yakovlevegor/DroidRec#18]
@drogga reported a crash on more than one recording on Android 9 with resolution `2220x1080`

**Comment by yakovlevegor** [comment]
I could create a version which records only 1080p, for testing purposes.

**Comment by yakovlevegor** [comment]
Actually are you getting a crash on landscape or on portrait?

**Comment by yakovlevegor** [comment]
Actually there's a function that narrows down resolution to 16:9, but it is enabled only for Android < 7.1. Perhaps newer versions should also be affected?

**Comment by drogga** [comment]
Last 3 times I tested was when rotating from portrait to landscape (both sensor positions\orientations) and my screen resolution is FHD+ 2220x1080, not like you wrote WQHD+ 2960x1440, which is a option too.

**Comment by yakovlevegor** [comment]
Okay. For the testing purposes I've made a build that narrows resolution to 16:9 and enforces it for Android 9.
[app-build-debug-forceresolution.zip](https://github.com/yakovlevegor/DroidRec/files/10031384/app-build-debug-forceresolution.zip)

**Comment by drogga** [comment]
Same, except that the rez. is 1080x1920.

**Comment by yakovlevegor** [comment]
Well, my theory is different this time. For Android 10+ implementation(with playback recording) there is an entirely different way to do the recording, using different APIs. It's not available on older versions of Android because writing video with `MediaMuxer` to a file descriptor isn't supported there. I've made a build that uses the newer APIs for Android 9, avoiding using `MediaRecorder`.
[app-build-debug-nomediarecorder.zip](https://github.com/yakovlevegor/DroidRec/files/10033422/app-build-debug-nomediarecorder.zip)

**Comment by drogga** [comment]
Updated over and it's still the same.

**Comment by yakovlevegor** [comment]
Then it's not related to recording. Gonna look some more.

**Comment by yakovlevegor** [comment]
Does recording on landscape work at all?

**Comment by yakovlevegor** [comment]
This could also relate to `MediaProjection` being recreated on each restart. I've set to to keep old `MediaProjection` on restart of the recording.
[app-build-debug-keepprojection.zip](https://github.com/yakovlevegor/DroidRec/files/10040348/app-build-debug-keepprojection.zip)

**Comment by drogga** [comment]
Yes, I can record in landscape, as long as I don't rotate, or launch I app that is portrait only (forced to be in the manifest).

Will check "keepProjection" one and report in couple on minutes, by a new comment, or edit this one.

**Comment by drogga** [comment]
Yes, I can record in landscape, as long as I don't rotate, or launch a app that is portrait only (forced to be in the manifest).

**Comment by yakovlevegor** [comment]
I'm fixing an issue, maybe related to naming of virtual screens. The new build will be in a second.

**Comment by drogga** [comment]
...damn stupid GitHub, I can't even react on a comment in mobile view or so much more things, no that the desktop view is feature packed...

**Comment by yakovlevegor** [comment]
Crashing stopped, but files won't get written(like you said, they are empty).

**Comment by drogga** [comment]
Even tho you edited the comment with "app-build-debug-keepprojection.zip", but since I'm curious and stubborn, I decided to test it just now anyways, and believe it or not - it works better than ever before, it even looks like it recorded the rotation from portrait<>landscape, but only once, rotating for a second time, restarts the recording from the beginning as a new file, but there are no 0 Bytes empty .mp4 files anymore and the notification isn't stuck, so it seems like you were (are) on the right path...

**Comment by drogga** [comment]
BTW, for some reason the media scanner didn't index 3 of the 4 test records I did, so they didn't show up in the gallery, but they were in my "save" folder of choice, which is /DCIM/Screenshots.
...in case this info helps...

**Comment by yakovlevegor** [comment]
I'm getting an `java.lang.SecurityException: Invalid media projection` in an emulator.

**Comment by drogga** [comment]
Try on a real device, it will probably work, emulators don't reflect well the real usage anyway.

**Comment by yakovlevegor** [comment]
I'm trying it for Android >= 10 version. There's a problem with a different recorder.

**Comment by drogga** [comment]
...or use it in VMOS Pro (unlocked mod) and 9 Pie Rom, I just tries it there.

**Comment by drogga** [comment]
I've read that if you create a developer samsung account, you should be able to use some points and get access to a real remote device by them, different devices, models with diff. A. vers.
There are also other similar services by others, but they are all paid.

...or use it in VMOS Pro (unlocked mod) with 9 Pie Rom, I just tried it there.

**Comment by yakovlevegor** [comment]
Seems like the problem is unsolvable. Each time the recording ends `MediaProjection` detaches, and you have to start it again. The workaround was to create `MediaProjection` with a saved key each time the recording restarts, but your device ROM has certain restrictions against it.

**Comment by yakovlevegor** [comment]
Example: https://github.com/pedroSG94/rtmp-rtsp-stream-client-java/issues/536

**Comment by yakovlevegor** [comment]
I've got a different idea once yet, but if that doesn't work all is lost. This time I'll just try releasing `VirtualScreen`, and stopping `MediaProjection` before overwriting it's value. I seem to have a lead of what kind of error you have. Specifically on Android 9 I get:
`java.lang.IllegalStateException: Cannot start already started MediaProjection`

**Comment by yakovlevegor** [comment]
Here is a build where I implemented it:
[app-build-debug-projectionerase.zip](https://github.com/yakovlevegor/DroidRec/files/10042156/app-build-debug-projectionerase.zip)

**Comment by drogga** [comment]
It works just as `app-build-debug-keepprojection.zip`, no errors or FC by the system and when rotating, it just splits it to another video,  so what do we expect to happen at this point, to seamlessly transition to the diff. orientation when rotated, without writing it to another file ?, because that would be great, but it's good enough for me for now, if I want to, I can merge the different \ separated clips into one video...

If it works for you on Android 10 and other OS ver., then I think that we can leave it be as the `projection erase` build.

**Comment by yakovlevegor** [comment]
@drogga, the reason the second file is required is to change the recording's resolution. If you, say, choose to record portrait and then transition to landscape, your recording will loose half of it's quality, because of this transition.

**Comment by yakovlevegor** [comment]
Thank you for assistance. I'm pushing the fix and including it in the next release.

**Comment by drogga** [comment]
Nice ;), I'm glad that I could assist\help with the testing to get it right.

Actually, I'm okay if the videos are the wrong orientation in order to not change the rez., like when recording in portrait and rotate to landscape the or the opposite, the one becomes too small at the center with black frames, but if it doesn't change that, it will be wrongly orientated, but if you tilt the device at the point\edge of rotating, but the sensor doesn't rotate it because it's not there yet, you can adjust yourself to see it correctly, but I can understand why none of the screen recorders I tried do this, because in players like VLC you can pinch to zoom on those "scenes" with black bars and low rez. and look them that way, other players also provide force rotating the video, which can help too.

BTW, I think that the user base target is A.5>9\10, because latest OS versions offer build-in system screen recorder, even AOSP, but I'm not sure...

**Comment by yakovlevegor** [comment]
Yeah, some ROMs have a built-in screen recorder, Samsung has one in their "Game Launcher". But I bet all of them are implemented within system-level APIs.

**Comment by drogga** [comment]
The one in the Game Launcher can be used as a workaround for S8, S9 and newer devices, even with 9 Pie have it with some advanced settings and it's a visible quick tile b default. They could easily add it to S8, but they didn't, just so they can offer something new in S9, so people would buy it, hence I need a screen rec. app on mine, because it's not convenient to go tru the Game Launcher everytime you need to record something real quck.

Most stock firmwares \ roms, custom ones to have a screen recorder, since A.10 or 11, actually I can probably barely find a device released in the last 3 years, that doesn't have it, that if a search for, I've seen it even on some cheap trash devices by diff. brands and I don't mean the big names, like Samsung, Xiaomi, Oppo, Vivo, RealMe, Huawei, OnePlus, HTC or Google.

**Comment by yakovlevegor** [comment]
Version [1.8](https://github.com/yakovlevegor/DroidRec/releases/tag/v1.8) is out. Fix is in the latest release, closing.
