### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by Reza478** [yakovlevegor/DroidRec#43]
If you make a good UI for your app it will be perfect.

**Comment by yakovlevegor** [comment]
Could you be more specific? What do you dislike in the current UI in particular?

**Comment by Reza478** [comment]
@yakovlevegor it is very good with no bug but if you keep updating this app it will be perfect.
Add some new features
Improve UI,

**Comment by carsten-engelke** [comment]
I do think it is a "real" issue. Most users will be distracted and non-techies might even erase the app before even using ist because it "looks different" and therefore "suspicious". The app is too good to be neglected imo! Take a look at Material Design, you shall add a Bar at the top with some hamburger menu to access settings (and the switches that are now the main background). Maybe add a FAB for instant recording. Main app focus could be the timer or a list of former recordings for easier sharing/deletion. I believe this would make the app look more professional (it very much deserves a new polish)

**Comment by yakovlevegor** [comment]
@Reza478 @carsten-engelke 
I'm sorry, but I don't know where this is going. You are urging me to change the UI without providing any slight hint on **how** you want it to be changed.
This looks more like a *motivational speech* to me, not an issue description.
I'm *not implementing* this.
